{{- if .Values.ingress.enabled -}}
 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
 spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - backend:
              serviceName: {{ .Values.service.name }}
              servicePort: 80
        {{- end }}
  {{- end }}
